name: Dependency Submission

on:
  push:
    branches: [ $default_branch ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto # AWS distribution
          java-version: 17

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3