on:
  workflow_call:

jobs:
  checkov-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@0a805cb037dd8386610e1d415770e237e211262d # v12.2925.0
        output_format: cli,sarif
        output_file_path: console,results.sarif
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@4fa2a7953630fd2f3fb380f21be14ede0169dd4f # v3.25.12v3
        with:
          sarif_file: results.sarif
