on:
  workflow_call:

jobs:
  checkov-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@fa45bce4384650003ab4f450b022372c3c13ef75 # v12.2824.0
        output_format: cli,sarif
        output_file_path: console,results.sarif
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@f6091c0113d1dcf9b98e269ee48e8a7e51b7bdd4 # v3.28.5
        with:
          sarif_file: results.sarif
